### ISSUE TITLE
Current Directory broken in version >= 2020a

### ISSUE THREAD

**Issue by elpollodiablo84** [elpollodiablo84/atom-matlab-editor#10]
Starting with Matlab R2020a, Mathworks stopped using `matlab.settings`  to save Matlab internal state: it now uses `matlab.mlsettings`, sadly not a plain text file.
We need another way to find the Matlab current directory, or we have to disable this functionality.

**Comment by MihailoPlavsic34** [comment]
Could running a script that uses the cd function to output current dir to a text file at a location we specify every time we require said input work?
Something like:

fileID = fopen('C:\Users\Admin\Desktop\test.txt', 'w');
s=cd;
fprintf (fileID,'%s' ,s);

Gives us this as an output:
[test.txt](https://github.com/elpollodiablo84/atom-matlab-editor/files/5715303/test.txt)

Changing the directory by any means gives us a different output:

Using the command cd 'C:\Users\Admin\Downloads' in Matlabs Command Window, and then running the script gives us:
[test.txt](https://github.com/elpollodiablo84/atom-matlab-editor/files/5715322/test.txt)

**Comment by elpollodiablo84** [comment]
I've literally found the solution while you were typing probably 😄 
The new configuration file `matlab.mlsettings` is a compressed archive, so unzipping and extracting the right file should do the trick.
Your solution is perfectly fine also, but my "philosophy" with this package is to do everything *externally* to Matlab, or at least try. This is why issue #1 is my recurrent nightmare 😅 ...
I will update the package accordingly, I hope soon enough. Thanks for your interest!

**Comment by MihailoPlavsic34** [comment]
No problem, I just discovered this package and I think it's amazing. You are doing excellent work!

**Comment by elpollodiablo84** [comment]
Ok, the issue should be resolved in the current version (0.5.0).
