### ISSUE TITLE
Try... catch... end 

### ISSUE THREAD

**Issue by aaronchungjukko** [elpollodiablo84/atom-matlab-editor#12]
Catch doesn't seem to be fully recognised in indentation and formatting.

**Comment by elpollodiablo84** [comment]
Could you post an example where indentation fails? 
(By the way the correct package to report this is issue is https://github.com/elpollodiablo84/language-matlab-plus)

**Comment by elpollodiablo84** [comment]
Closing this since doesn't affects this package.
