### ISSUE TITLE
Failed to load nativenvm library

### ISSUE THREAD

**Issue by TomSuarezO** [elpollodiablo84/atom-matlab-editor#13]
Hello, I am attempting to run Matlab files with the atom-matlab-editor. I added the share engine line of code on Matlab's startup. When I try to run a code I get the error message saying "Failed to load nativenvm library: no nativevm in java.library.path"

My computer architecture is Windows x64 and I am running R2020b. 
![image](https://user-images.githubusercontent.com/45014122/115440377-ab606e00-a1dd-11eb-8294-5503e0a0b788.png)

**Comment by elpollodiablo84** [comment]
As suggested in the readme, add the correct path to your environmental variables as explained [this MATLAB Answers thread](https://mathworks.com/matlabcentral/answers/320234-using-java-api-gives-no-nativemvm-in-java-library-path#answer_259968), and then restart Atom.
