### ISSUE TITLE
Keybindings not working...?

### ISSUE THREAD

**Issue by mannyjrod** [elpollodiablo84/atom-matlab-editor#14]
Hello, the Keybindings don't seem to be working. Am I missing something? Thanks!
![image](https://user-images.githubusercontent.com/72452084/119570717-bde63e00-bd6d-11eb-9a97-6ff52cca897d.png)

**Comment by elpollodiablo84** [comment]
I don't know if there are some problems with keybindings, but I see an error in your configuration: you have to type `computer('arch')` in your Matlab command window and write the result in the package settings. For example, if you have Windows it should be `win64`.
Let me know if this fixes your problems.

**Comment by elpollodiablo84** [comment]
I'll close this issue for the lack of feedback, but I'll re-open it if needed.
