### ISSUE TITLE
Can't find the  path of atom-matlab-editor in Ubuntu 18

### ISSUE THREAD

**Issue by AlfredoDB** [elpollodiablo84/atom-matlab-editor#17]
Hello,

I am trying to install the atom-matlab-editor in ubuntu 18,  but when I have to enter the set path in Matlab I can't find it. The path proposed in the information works in Windows, but not in Ubuntu.

Please can you help me.

Thank you.

Regards.

Alfredo de Blas

**Comment by elpollodiablo84** [comment]
>[...] but when I have to enter the set path in Matlab I can't find it

Which "path" are you referring to? The Matlab search path? Or one of the "config dir", like `tempdir` or `matlabdir`?
In the first case you can find some info [there](https://it.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html), in the latter you have to follow the instructions specified in this package readme (not dependent on your platform).

**Comment by AlfredoDB** [comment]
Thank you for your answer. 

In am referring to the search path in Matlab. In the info it is: "[...]\.atom\packages\atom-matlab-editor\lib\java", but in Ubuntu 18 I can't find the directory of atom-matlab-editor.
