### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by aaronchungjukko** [elpollodiablo84/atom-matlab-editor#2]
[Enter steps to reproduce:]

1. ... MATLAB version R2019b, I know this isn't technically supported.
2. ... Follow steps for installation as asked
3. ... path settings: win64, C:\Program Files\MATLAB\R2019b\, \\icnas4.cc.ic.ac.uk\hlc15\appdata\MathWorks\MATLAB\R2019b, C:\Users\hlc15\AppData\Local\Temp\
4. ... press F5 to run MATLAB

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-matlab-editor](https://github.com/elpollodiablo84/atom-matlab-editor) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At C:\Users\hlc15\.atom\packages\atom-matlab-editor\lib\atom-matlab-editor.js:222

TypeError: Cannot read property 'add' of null
    at Object.runFile (/packages/atom-matlab-editor/lib/atom-matlab-editor.js:222:33)
    at /packages/atom-matlab-editor/lib/atom-matlab-editor.js:131:61)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -8:22.2.0 application:reopen-project (input.hidden-input)
     -8:20 atom-matlab-editor:run-file (input.hidden-input)
  9x -6:51 core:backspace (input.hidden-input)
  2x -4:35.1.0 atom-matlab-editor:get-help (input.hidden-input)
     -4:23 atom-matlab-editor:run-file (input.hidden-input)
     -4:06.0 core:backspace (input.hidden-input)
     -3:53.5.0 atom-matlab-editor:run-file (input.hidden-input)
     -3:49.3.0 core:undo (div.package-detail)
  4x -3:43.9.0 atom-matlab-editor:run-file (input.hidden-input)
  5x -2:34.5.0 core:backspace (input.hidden-input)
     -2:29.8.0 core:delete (input.hidden-input)
  2x -2:28.9.0 core:backspace (input.hidden-input)
  2x -2:22.7.0 atom-matlab-editor:run-file (input.hidden-input)
     -1:58.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:55.8.0 editor:consolidate-selections (input.hidden-input)
     -1:55.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-matlab-editor 0.1.0 
language-matlab-plus 1.12.0 
```

**Comment by elpollodiablo84** [comment]
Ok, that's strange: the error is thrown because you haven't installed the package `busy-signal`, which `atom-matlab-editor` needs in its dependencies. The strange parts is that I thought Atom would install it along with `atom-matlab-editor`. Maybe you uninstalled it?
However, try to install [`busy-signal`](https://atom.io/packages/busy-signal) and let me know if everything works.

**Comment by aaronchungjukko** [comment]
Perfect! Thank you. It took me a while to figure out how to add environment variables after fixing this error but found the simple windows settings for that as well.

**Comment by elpollodiablo84** [comment]
If you think that the instructions are not clear enough, let me know it. I probably consider obvious something that it isn't obvious at all!
Feel free to open another issue in that case, we can work on it.
