### ISSUE TITLE
Save and Run?

### ISSUE THREAD

**Issue by aaronchungjukko** [elpollodiablo84/atom-matlab-editor#3]
Sorry I have been trying for hours but just couldn't figure out how to save and run. Any help would be appreciated. This is half a feature request but really I know I should be able to do it in init.coffee, but just nothing has worked: I'm not sure how I could make it just call atom-matlab-editor:run-file as a command.

`atom.commands.add 'atom-workspace', 'custom:SaveAndRun', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.save()
  atom.commands.dispatch(editor, 'atom-matlab-editor:run-file()')`

**Comment by elpollodiablo84** [comment]
That seems a good feature request, I'll implement it.
I'm not sure why your approach doesn't work, I'm not a good JS programmer (actually I'm not a good programmer 😊), probably you cant use `atom.commands.add` like that in your `init.coffee` since it returns a Disposable, but whatever. Just wait for the next version!

**Comment by aaronchungjukko** [comment]
Thanks!

Do you know why MATLAB's workspace doesn't show the working variables of a
given program that I run from atom-matlab-editor? (this might be another
feature request 😂)

Best Regards,
Aaron

**Comment by elpollodiablo84** [comment]
> Do you know why MATLAB's workspace doesn't show the working variables of a given program that I run from atom-matlab-editor?

After executing a script from Atom you should be able to see every created variable in the Matlab workspace. This package basically tells Matlab to run a file, so everything should work as called by Matlab itself.

Unless you are talking about debug mode: unfortunately it can't be done without calling the Matlab editor, so it's not possible to do in Atom (by me, at least).

**Comment by aaronchungjukko** [comment]
I looked at it again and if seems to be working today! I swear it wasn't
working yesterday 😂
Maybe I should debug my brain instead. Thanks for your help anyways!

**Comment by elpollodiablo84** [comment]
To be fair, your brain maybe doesn't need a debug, because sometimes Matlab fails to realize that a file has been modified by an external editor, causing the weirdest problems.
Remember, when in doubt, blame Matlab!
