### ISSUE TITLE
Error running a simple disp

### ISSUE THREAD

**Issue by aminya** [elpollodiablo84/atom-matlab-editor#4]
![image](https://user-images.githubusercontent.com/16418197/78692791-03bd1a00-78c0-11ea-81c7-52aad4ff16fe.png)

**Comment by aminya** [comment]
Solved by https://www.mathworks.com/matlabcentral/answers/320234-using-java-api-gives-no-nativemvm-in-java-library-path# and restarting Atom

Maybe we should do this automatically in the first install.

**Comment by aminya** [comment]
I noticed this is mentioned in the Readme. It would be good to add `atom.notifications.addWarn("Please read Readme for installation")`.

**Comment by elpollodiablo84** [comment]
> I noticed this is mentioned in the Readme. It would be good to add `atom.notifications.addWarn("Please read Readme for installation")`.

Good idea, but I don't know if I can detect this error since it's a Java error not thrown by Matlab, but I can try to catch it. I'll close this issue and open another with this suggestion.
